"""Generate importable Python modules from piecewise fit results."""

from __future__ import annotations

import re
from typing import Any

from final_setup.piecewise import FunctionFamily, PiecewiseFitResult

_TRANSFORM_EXPR = {
    "linear": "x",
    "log": "math.log10(x)",
    "sqrt": "math.sqrt(x)",
}


def _sanitize(name: str) -> str:
    cleaned = re.sub(r"[^0-9a-zA-Z_]+", "_", name.strip())
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    if not cleaned:
        raise ValueError("name must contain at least one alphanumeric character")
    if cleaned[0].isdigit():
        cleaned = f"_{cleaned}"
    return cleaned


def _format_float(value: float) -> str:
    text = f"{value:.12g}"
    return text if text else "0.0"


def _line_expr(slope: float, intercept: float, family: FunctionFamily) -> str:
    t = _TRANSFORM_EXPR[family]
    if intercept >= 0:
        return f"{_format_float(slope)} * ({t}) + {_format_float(intercept)}"
    return f"{_format_float(slope)} * ({t}) - {_format_float(abs(intercept))}"


def generate_fit_module(
    *,
    x_col: str,
    y_col: str,
    result: PiecewiseFitResult,
    meta: dict[str, Any],
    module_name: str | None = None,
) -> str:
    """Return Python source: named functions + FUNCTIONS dict."""
    prefix = _sanitize(y_col)
    mod = module_name or f"fit_{_sanitize(y_col)}_from_{_sanitize(x_col)}"
    lines_sorted = sorted(result.lines, key=lambda line: line[0])

    fn_blocks: list[str] = []
    dict_entries: list[str] = []

    for j, (slope, intercept) in enumerate(lines_sorted, start=1):
        fn_name = f"{prefix}_line_{j}"
        expr = _line_expr(slope, intercept, result.function_family)
        fn_blocks.append(
            f"def {fn_name}(x: float) -> float:\n"
            f'    """{y_col} from {x_col}: y = {expr}"""\n'
            f"    return {expr}\n"
        )
        dict_entries.append(f'    "{fn_name}": {fn_name},')

    meta_lines = [
        f'    "x_col": {_repr_str(x_col)},',
        f'    "y_col": {_repr_str(y_col)},',
        f'    "k": {result.k},',
        f'    "function_family": {_repr_str(result.function_family)},',
        f'    "mse": {_format_float(result.mse)},',
        f'    "counts": {list(result.counts)!r},',
        f'    "n_points": {meta.get("n_points", "None")},',
        f'    "n_fit_points": {meta.get("n_fit_points", "None")},',
        f'    "n_outliers_removed": {meta.get("n_outliers_removed", 0)},',
    ]
    if meta.get("anchor_x") is not None:
        meta_lines.append(f'    "anchor_x": {_format_float(float(meta["anchor_x"]))},')
    if meta.get("anchor_y") is not None:
        meta_lines.append(f'    "anchor_y": {_format_float(float(meta["anchor_y"]))},')

    coef_lines = []
    for j, (slope, intercept) in enumerate(lines_sorted, start=1):
        coef_lines.append(
            f'        {{"name": "{prefix}_line_{j}", "slope": {_format_float(slope)}, '
            f'"intercept": {_format_float(intercept)}}},'
        )

    return f'''\
"""Auto-generated by Ablations Plot Explorer — {mod}"""

from __future__ import annotations

import math
from typing import Callable

FIT_META = {{
{chr(10).join(meta_lines)}
    "lines": [
{chr(10).join(coef_lines)}
    ],
}}

{chr(10).join(fn_blocks)}
FUNCTIONS: dict[str, Callable[[float], float]] = {{
{chr(10).join(dict_entries)}
}}
'''


def _repr_str(value: str) -> str:
    return repr(value)
